### ISSUE TITLE
click on linkText("foo") does not compile

### ISSUE THREAD

**Issue by mb73** [agido/pageobject#2]
`QueryDsl.linkText()` returns a LinkTextQuery. The doc says:
> This method enables syntax such as the following: click on linkText("???") 

But `ClickDsl.on()` wants an `Element `or a `Locator`, not a `Query`. 
So this does not compile: `click on linkText("foo")`

> Error:(23, 13) overloaded method value on with alternatives:
>   [E <: org.pageobject.core.api.Element](locator: org.pageobject.core.api.Locator[E])Unit <and>
>   [E <: org.pageobject.core.api.Element](element: E)Unit
>  cannot be applied to (org.pageobject.core.api.LinkTextQuery)
>       click on linkText("foo")

**Comment by drieks** [comment]
Hi,

you are right, this is a leftover from scalatest page object implementation.

Quick fix: click on $(linkText("foo"))

The problem is that that the scalatest implementation does not check how many elements are selected by the query. Because every query can return [0..n] Elements there is no clear way to handle no elements found or more then one element found.

The way to handle this in pageobject is:
* create a Query
maybe linkText("foo") or cssSelector(".some.class")
Query -> what should be selected
* pass the query to a locator 
the locator will bind the Query to the PageObject and provides (some examples)
* element: Element
this is using assert(elements.size == 1)
* elementOption: Option[Element]
this is using assert(elements.isEmpty || elements.size == 1)
* elements: Seq[Element]
If you expect no elements or more then one you can use this to iterate over all Elements [but clicking more then Elements makes no sense]

There is a implicit conversation from Locator to Element. So if a function expects an Element you can pass also a Locator, forcing the "assert(elements.size == 1)" by implicit calling "locator.element" in this case.

**Comment by drieks** [comment]
There a different types of Locator:
* UntypedLocator [created by calling $(...)]
this locator will create an Element for every DOM Node returned by the query.
Use this Locator if you try to select a <div> or <span>
* <Type>Locator, e.q. ButtonLocator:
This locator will check the type of the DOM Node returned by the Query and will fail the Test if the node is of an unexpected type.
There are may Locator types, have a look at https://github.com/agido/pageobject/blob/master/core/src/main/scala/org/pageobject/core/api/Locator.scala or https://github.com/agido/pageobject/blob/master/core/src/main/scala/org/pageobject/core/dsl/LocatorDsl.scala to see all available locators.

Use this type of Locators if you expect a special type of Element, like Form Elements.

**Comment by drieks** [comment]
Recommented usage is like here:
https://github.com/agido/pageobject/blob/master/examples/src/test/scala/org/pageobject/examples/wikipedia/WikipediaSearchModule.scala#L23

```scala
trait ExampleModule extends PageModule {
  // $ -> UntypedLocator, we expect a div or something
  // linkText -> we select elements by linkText
  private val foo = $(linkText("foo"))

  def click(): Unit = {
    // foo.element is invoked here,
    // the test will fail if no element (or more then one) is found
    click on foo
  }

  // other example
  // singleSel -> we expect a single selection dropdown form element
  // cssSelector -> we select Elements by using a css query
  private val foo2 = singleSel(cssSelector("#someid .foo"))
}
```

**Comment by drieks** [comment]
Hello @mb73,

I have fixed the documentation. Thank you for reporting this!

Please let me know if you have any questions.

**Comment by mb73** [comment]
I see. So `click on $(linkText("foo"))` is short for `click on $(linkText("foo")).element`. Thanks!

As I can see, e.g. `click on $(linkText("foo")).elements` is not defined. Is that on purpose, because the usecase is unprobable or because `$(linkText("foo")).elements.foreach(click on)` is also readable? I do not have such a usecase yet, I must admit :) Just being curious.

**Comment by drieks** [comment]
Hi mb73,

`$(linkText("foo")).elements` is defined, but `click.on()` does not accept a collection:
```scala
val elements: Seq[UntypedElement] = $(linkText("foo")).elements`
click on elements // it makes no sense to pass more then one element to click, so Seq[UntypedElement] is not allowed here
```

You should assign the locator to a var because it is immutable and can therefore be reused, it is also better to read because it is shorter:

```scala
trait ExampleModule extends PageModule {
  private val foo = $(linkText("foo"))

  def click(): Unit = {
    click on foo // ok
    click on foo.element // ok, but the first variant is better to read
    foo.elements.foreach(element => click on element) // ok (but you should not click all elements because a user can not do this)
  }
}
```

(the val should also be private because a page module should hide the implementation [the $(..) part] and just provide a scala api)

**Comment by mb73** [comment]
> // ok (but you should not click all elements because a user can not do this)

Why can't a user do this? A user can click on 20 elements (e.g. checkboxes), one after the other.

**Comment by drieks** [comment]
Hi,

by calling the methods on the Element (or a Locator) you are invoking selenium commands that are executed immediately and in an very short timeframe. This are no actions that a user can do, except clicking and typing text.

Selenium has no control over the mouse pointer, is will just detect the x/y location and the with/height of the element and simulate a click at this point (but if another element is at this location, maybe a overlapping drop down list, the click will fail)

The user needs some time to move the mouse cursor from element to element between clicks, this is not simulated. A developer typically whats to click only one element and this element should be unambiguous. If you have two buttons, maybe "ok" and "cancel" selected by one selector and you call `click on theSelector` the browser will try to process the ok click. but because of timing problems even cancel can be processed first sometimes. This will result in nondeterministic test runs.

Another problem is that if the test expects to click the ok button, but the ok button is not visible or clickable, it will just click cancel and tell you everything was alright, like "ok, I clicked the button/buttons for you, what should I do next?".

It is better to catch such errors early, if the test fails with "there is no ok button to click", "the ok button is not clickable" or even "there is more than one element to click" is easy to read and you don't have to debug the test.

Imagine you have a register test that don't enable the register button unless the "Terms and Conditions" checkbox was clicked. you have a selector for register and cancel buttons, both redirecting to the homepage.

If the registration form will be changed so that you have to scroll down the terms scrollbox first before you can check the checkbox, your test can still succeed because it just clicks the cancel button instead of the register button.

ok, this is a theoretical example where other parts could be also improved, but is shows you why I think it is better to not allow clicking multiple elements at the same time.

if you really really want you can use `selector.foreach(_.click())` to force this.

You mentioned checkboxes: there are for almost all html form elements special selectors that are returning elements with additional functions:
https://github.com/agido/pageobject/blob/master/core/src/main/scala/org/pageobject/core/api/Element.scala#L607

```scala
trait ExampleModule extends PageModule {
  // ok, this is a bad example because a checkbox never has a linkText
  // because of this you can never work with foo because you will always get an exception..
  // just change it another query like checkbox(id("foo"))
  private val foo = checkbox(linkText("foo"))

  def click(): Unit = {
    foo.select() // check
    foo.clear() // uncheck
    foo.click() // just toggle
  }
}
```

ok this is very long.. please let me know if you have any questions!

**Comment by mb73** [comment]
Dennis, thanks for clarifying! 
Regards, Marcus
PS: I enjoyed your article in Java Magazin 11.16. Any idea when the second part will be published?

**Comment by drieks** [comment]
Hi, gladly done!

It will be published in (german) Java Magazin 1/2017 (available Monday, December 12th)

First part
magazine: https://jaxenter.de/ausgaben/java-magazin-11-16
article preview: https://entwickler.de/leseproben/automatisch-praktisch-gut-automatisiertes-testen-285711.html

Second part
https://jaxenter.de/ausgaben/java-magazin-1-17 [not yet online]
